// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/18/2026, 9:48:29 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/trong/Downloads/ttrda-/ttrda-/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/trong/Downloads/ttrda-/ttrda-/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/trong/Downloads/ttrda-/ttrda-/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/trong/Downloads/ttrda-/ttrda-/src/plugins/**/*.{js,ts,mjs}","C:/Users/trong/Downloads/ttrda-/ttrda-/src/composables/**/*.{js,ts,mjs}","C:/Users/trong/Downloads/ttrda-/ttrda-/src/utils/**/*.{js,ts,mjs}","C:/Users/trong/Downloads/ttrda-/ttrda-/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/trong/Downloads/ttrda-/ttrda-/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/trong/Downloads/ttrda-/ttrda-/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/trong/Downloads/ttrda-/ttrda-/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;